### ISSUE TITLE
Service seems to crash and encoder does not produce correct values

### ISSUE THREAD

**Issue by r0ckarong** [PM84/phoniebox_helper#4]
The problem seems to be that the result of "playout_controls.sh -c=getvolume" is an empty string with a newline. I don't know why this would be.

```
Apr 12 17:29:32 phoniebox PhonieboxRotaryControl[4124]: Traceback (most recent call last):
Apr 12 17:29:32 phoniebox PhonieboxRotaryControl[4124]:   File "/home/pi/phoniebox_rotary_control/scripts/controller/./rotary_volume_control.py", line 109, in <module>
Apr 12 17:29:32 phoniebox PhonieboxRotaryControl[4124]:     setVolume(readVolume(), event.event.value * getVolumeStep())
Apr 12 17:29:32 phoniebox PhonieboxRotaryControl[4124]:   File "/home/pi/phoniebox_rotary_control/scripts/controller/./rotary_volume_control.py", line 38, in readVolume
Apr 12 17:29:32 phoniebox PhonieboxRotaryControl[4124]:     return int(value)
Apr 12 17:29:32 phoniebox PhonieboxRotaryControl[4124]: ValueError: invalid literal for int() with base 10: '\n'
Apr 12 17:29:32 phoniebox systemd[1]: phoniebox-rotary-control.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 17:29:32 phoniebox systemd[1]: phoniebox-rotary-control.service: Failed with result 'exit-code'.
Apr 12 17:29:32 phoniebox systemd[1]: phoniebox-rotary-control.service: Scheduled restart job, restart counter is at 3.
Apr 12 17:29:32 phoniebox systemd[1]: Stopped Phoniebox Rotary Control Service.
Apr 12 17:29:32 phoniebox systemd[1]: Started Phoniebox Rotary Control Service.
Apr 12 17:29:33 phoniebox PhonieboxRotaryControl[4224]: Traceback (most recent call last):
Apr 12 17:29:33 phoniebox PhonieboxRotaryControl[4224]:   File "/home/pi/phoniebox_rotary_control/scripts/controller/./rotary_volume_control.py", line 109, in <module>
Apr 12 17:29:33 phoniebox PhonieboxRotaryControl[4224]:     setVolume(readVolume(), event.event.value * getVolumeStep())
Apr 12 17:29:33 phoniebox PhonieboxRotaryControl[4224]:   File "/home/pi/phoniebox_rotary_control/scripts/controller/./rotary_volume_control.py", line 38, in readVolume
Apr 12 17:29:33 phoniebox PhonieboxRotaryControl[4224]:     return int(value)
Apr 12 17:29:33 phoniebox PhonieboxRotaryControl[4224]: ValueError: invalid literal for int() with base 10: '\n'
Apr 12 17:29:33 phoniebox systemd[1]: phoniebox-rotary-control.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 17:29:33 phoniebox systemd[1]: phoniebox-rotary-control.service: Failed with result 'exit-code'.
Apr 12 17:29:33 phoniebox systemd[1]: phoniebox-rotary-control.service: Scheduled restart job, restart counter is at 4.
Apr 12 17:29:33 phoniebox systemd[1]: Stopped Phoniebox Rotary Control Service.
Apr 12 17:29:33 phoniebox systemd[1]: Started Phoniebox Rotary Control Service.
```

**Comment by PM84** [comment]
Should be fixed with recent release.
